version: "3.4"

services:
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=symfony
      - MYSQL_USER=symfony
      - MYSQL_PASSWORD=symfony
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - ./mysql/my.cnf:/etc/mysql/my.cnf
